# SPDX-License-Identifier: MIT
---

- name: Set platform/version specific variables
  include_vars: "{{ __crypto_policies_vars_file }}"
  loop:
    - "{{ ansible_facts['os_family'] }}.yml"
    - "{{ ansible_facts['distribution'] }}.yml"
    - "{{ ansible_facts['distribution'] ~ '_' ~
          ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['distribution'] ~ '_' ~
          ansible_facts['distribution_version'] }}.yml"
  vars:
    __crypto_policies_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: __crypto_policies_vars_file is file

- name: Ensure required packages are installed
  package:
    name: "{{ __crypto_policies_packages }}"
    state: present

- include_tasks: gather_facts.yml

- name: Find base policies files
  find:
    paths:
      - /usr/share/crypto-policies/policies/
      - /etc/crypto-policies/policies/
    patterns: '*.pol'
  register: __crypto_policies_base_policies

- name: Set available base policies fact
  set_fact:
    crypto_policies_available_policies: >-
      {{ __crypto_policies_base_policies.files | map(attribute='path')
        | map('basename') | map('splitext') | map('first') | unique | list }}
    cacheable: true

- name: Find policy module files
  find:
    paths:
      - /usr/share/crypto-policies/policies/modules/
      - /etc/crypto-policies/policies/modules/
    patterns: '*.pmod'
  register: __crypto_policies_policy_module

- name: Set available policy modules fact
  set_fact:
    crypto_policies_available_modules: >-
      {{ __crypto_policies_policy_module.files | map(attribute='path')
        | map('basename') | map('splitext') | map('first') | unique | list }}
    cacheable: true

- name: Update crypto policy if needed
  command: >
    update-crypto-policies
      {{ '--no-reload' if not crypto_policies_reload else '' }}
      --set {{ crypto_policies_policy }}
  when:
    # TODO check with available policies and modules
    - crypto_policies_policy is not none
    - crypto_policies_policy != crypto_policies_active
  notify: __crypto_policies_handler_modified

- name: Set the reboot_required flag if needed
  set_fact:
    crypto_policies_reboot_required: true
  when:
    # TODO check with available policies and modules
    - crypto_policies_policy is not none
    - crypto_policies_policy != crypto_policies_active

# Update the facts after applying the policy
- include_tasks: gather_facts.yml
